<a href="https://colab.research.google.com/github/Muchee-ai/Numpy-practice/blob/main/1_asoslar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4, 5]) #massiv yaratish
a

array([1, 2, 3, 4, 5])

In [ ]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) #ko'p o'lchovli massiv
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.zeros(10) #barcha elementlari 0ga teng

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 3)) #3ga 3 o'lchamli 0ga teng massiv

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(10) #barcha elementlar 1ga teng

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full((3, 3), 7) #3ga 3 o'lchamli ixtiyoriy songa teng

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
np.eye(3) # birlik matritsa (diagonalda 1)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.arange(10) #arange funksiyasi(qadamlarni biz belgilaymz)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2, 20, 2) #2dan 20gacha 2qadamlik massiv

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

Linspace - nechta element kerakligini aytamz, qadam o'zi hisoblanadi. Oxirgi son kiradi. Odatda grafik chizishda ishlatiladi.

In [ ]:
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Massiv atributlari(shape,ndim,size,dtype,itemsize)

In [ ]:
numbers = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
numbers

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
numbers.shape #shakli: 2qator va 4ustundan iborat

(2, 4)

In [ ]:
numbers.ndim #o'lchovlar soni

2

In [ ]:
numbers.size #jami elementlar soni

8

In [ ]:
numbers.dtype #element turi

dtype('int64')

In [ ]:
numbers.itemsize #bitta element necha bayt ekanligi

8