<a href="https://colab.research.google.com/github/Muchee-ai/Numpy-practice/blob/main/2-slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([10, 20, 30, 40, 50, 60, 70])

In [3]:
b = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12]])

In [4]:
a[0] #index orqali 0chi elementni chaqirish

np.int64(10)

In [6]:
a[6] #index orqali 6chi element

np.int64(70)

In [7]:
a[-7] #oxirgisi

np.int64(10)

In [9]:
b[0,0] #ko'p o'lchovli massivda(0-qator,0-ustun)

np.int64(1)

In [10]:
b[2,2] #2-indexdagi qator va 2-ustun

np.int64(11)

Kesish(slicing)

In [11]:
a[2:5] #2dan 5gacha bo'gan elementlar

array([30, 40, 50])

In [12]:
a[:5] #boshidan 5gacha bo'gan barchasi

array([10, 20, 30, 40, 50])

In [13]:
a[4:] #4dan keyingi barchasi

array([50, 60, 70])

In [5]:
sliced_arr = a[3:5]
sliced_arr[:] = 0
sliced_arr

array([0, 0])

In [6]:
a

array([10, 20, 30,  0,  0, 60, 70])

Copy usuli

In [7]:
arr1 = np.arange(10,100,10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
sliced_arr1 = arr1[3:5].copy()
sliced_arr1[:]=0
sliced_arr

array([0, 0])

In [9]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

2 o'lchamli(2d array) massivlarda

In [11]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
arr2[1, 3] #1-qatorning 3-ustuni

np.int64(8)

In [17]:
arr2[2, 0:4] #2-qatorning 0dan 4-chiga ustunlari

array([ 9, 10, 11, 12])

3 o'lchamli(3D) massivlar

In [19]:
arr3D = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]] )
arr3D

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [21]:
arr3D[0]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
arr3D[0][1, 1]

np.int64(6)

In [24]:
arr3D[1][1, 2]

np.int64(7)

In [26]:
arr3D[1][1, 0:4]

array([5, 6, 7, 8])

Boolean indekslash

In [27]:
names = np.array(['Hasan', 'Husan', 'Otabek', 'Dilmurod', 'Husan', 'Javohir'])
names

array(['Hasan', 'Husan', 'Otabek', 'Dilmurod', 'Husan', 'Javohir'],
      dtype='<U8')

In [29]:
data = np.random.randn(6,4)
data

array([[ 0.659557  ,  0.07422659, -0.60107702, -0.32691233],
       [ 0.21995611,  0.75092761, -0.78700116,  0.34965231],
       [-0.10303023, -1.47955117, -0.57495641,  2.27261539],
       [ 1.39391415,  1.99124566, -0.70227601, -1.91460203],
       [-0.96079577,  1.76798834, -0.69026485, -1.64352287],
       [ 0.4230853 , -1.87986115, -0.91893561,  0.81748982]])

In [30]:
names == 'Hasan'

array([ True, False, False, False, False, False])

In [31]:
data[names == 'Hasan'] #Hasanga tegishli barcha ma'lumotlar

array([[ 0.659557  ,  0.07422659, -0.60107702, -0.32691233]])

In [32]:
data[names == 'Husan'] #Husanga tegishli barcha ma'lumotlar

array([[ 0.21995611,  0.75092761, -0.78700116,  0.34965231],
       [-0.96079577,  1.76798834, -0.69026485, -1.64352287]])

In [33]:
data[names == 'Javohir', 2:] #Javohga tegishli oxrgi 2ta ustundagi ma'lumotlar

array([[-0.91893561,  0.81748982]])

In [34]:
data[names != 'Hasan'] #Hasandan tashqari barcha insonlarni ma'lumotlari

array([[ 0.21995611,  0.75092761, -0.78700116,  0.34965231],
       [-0.10303023, -1.47955117, -0.57495641,  2.27261539],
       [ 1.39391415,  1.99124566, -0.70227601, -1.91460203],
       [-0.96079577,  1.76798834, -0.69026485, -1.64352287],
       [ 0.4230853 , -1.87986115, -0.91893561,  0.81748982]])

In [35]:
data[~(names == 'Hasan')] #(~)yuqoridagi cell bn brxil natija

array([[ 0.21995611,  0.75092761, -0.78700116,  0.34965231],
       [-0.10303023, -1.47955117, -0.57495641,  2.27261539],
       [ 1.39391415,  1.99124566, -0.70227601, -1.91460203],
       [-0.96079577,  1.76798834, -0.69026485, -1.64352287],
       [ 0.4230853 , -1.87986115, -0.91893561,  0.81748982]])

In [36]:
print(names)
print(data)

['Hasan' 'Husan' 'Otabek' 'Dilmurod' 'Husan' 'Javohir']
[[ 0.659557    0.07422659 -0.60107702 -0.32691233]
 [ 0.21995611  0.75092761 -0.78700116  0.34965231]
 [-0.10303023 -1.47955117 -0.57495641  2.27261539]
 [ 1.39391415  1.99124566 -0.70227601 -1.91460203]
 [-0.96079577  1.76798834 -0.69026485 -1.64352287]
 [ 0.4230853  -1.87986115 -0.91893561  0.81748982]]


In [37]:
mask = (names == 'Hasan') | (names == 'Husan') #hasan/husanga tegishli ma'lumotlar
mask

array([ True,  True, False, False,  True, False])

In [38]:
data[mask]

array([[ 0.659557  ,  0.07422659, -0.60107702, -0.32691233],
       [ 0.21995611,  0.75092761, -0.78700116,  0.34965231],
       [-0.96079577,  1.76798834, -0.69026485, -1.64352287]])