<a href="https://colab.research.google.com/github/Muchee-ai/Numpy-practice/blob/main/2-Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([10, 20, 30, 40, 50, 60, 70])

In [3]:
b = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12]])

In [4]:
a[0] #index orqali 0chi elementni chaqirish

np.int64(10)

In [6]:
a[6] #index orqali 6chi element

np.int64(70)

In [7]:
a[-7] #oxirgisi

np.int64(10)

In [9]:
b[0,0] #ko'p o'lchovli massivda(0-qator,0-ustun)

np.int64(1)

In [10]:
b[2,2] #2-indexdagi qator va 2-ustun

np.int64(11)

Kesish(slicing)

In [11]:
a[2:5] #2dan 5gacha bo'gan elementlar

array([30, 40, 50])

In [12]:
a[:5] #boshidan 5gacha bo'gan barchasi

array([10, 20, 30, 40, 50])

In [13]:
a[4:] #4dan keyingi barchasi

array([50, 60, 70])