<a href="https://colab.research.google.com/github/Muchee-ai/Numpy-practice/blob/main/3-shaklni%20o'zgartirish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Massivlar pozitsiyasini ko'chirish(Transpose), o'qlar o'rnini almashtirish(swapping axis)

In [7]:
a = np.arange(6).reshape(3,2) #reshape metodi orqali
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
a.T #a massivning transpose ko'rinishi

array([[0, 2, 4],
       [1, 3, 5]])

In [13]:
np.dot(a, a.T)

array([[ 5, 14],
       [14, 50]])

In [18]:
a.reshape(2, -1)

array([[0, 1, 2],
       [3, 4, 5]])

ravel va flatten — yassilash (Ikkalasi ham ko'p o'lchovli massivni bir qatorga aylantiradi:)

In [4]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
b.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
b.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

farqlari

In [7]:
c = b.ravel()
c[0]=999
c

array([999,   2,   3,   4,   5,   6,   7,   8])

In [8]:
print(b) #b massivning elementni o'zgardi

[[999   2   3   4]
 [  5   6   7   8]]


.T va reshape farqi

In [21]:
number = np.array([1, 2, 3, 4, 5, 6])
number

array([1, 2, 3, 4, 5, 6])

In [32]:
a = number.reshape(3, 2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [33]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])