<a href="https://colab.research.google.com/github/Muchee-ai/Numpy-practice/blob/main/4-universal-funksiyalar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Unary funksiyalar (bitta argument qabul qiladi)
[sqrt, square, exp, log, modf, sign, isnan]

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.sqrt(arr) #massivning harbir elementini ildizni qaytaradi

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
np.square(arr) #masssivning harbir elementini kvadratga oshiradi

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
np.exp(arr) #elementlarni eksponentini qaytaradi

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [11]:
np.log(arr[1:]) #massivning harbir elementini logarifmini qaytaradi

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

modf - haqiqy sonlarni butun va qoldiq qismlarga ajratib beruvchi funksiya


In [12]:
arr = np.random.randn(6)
arr

array([ 0.06277197,  0.47566384, -0.5245436 ,  0.91974687, -0.13051867,
       -1.47713104])

In [13]:
butun, qoldiq = np.modf(arr)
print(butun)
print(qoldiq)


[ 0.06277197  0.47566384 -0.5245436   0.91974687 -0.13051867 -0.47713104]
[ 0.  0. -0.  0. -0. -1.]


In [14]:
np.isnan(arr) #massivdagi qaysi elementlar NaN ekanini tekshiradi.

array([False, False, False, False, False, False])

In [15]:
np.sign(arr) #sonning ishorasini qaytaradi. Ya'ni son musbatmi, manfiymi yoki nolmi.

array([ 1.,  1., -1.,  1., -1., -1.])

Binary funksiyalar(ikkita argument qabul qiladi) (add, multiple, maximum)

In [16]:
arr1 = np.random.randn(6)
arr2 = np.random.randn(6)


In [17]:
arr1


array([ 0.79713464, -0.48725024,  1.0060556 ,  0.94390042, -1.74701582,
       -0.56789593])

In [18]:
arr2

array([-2.0741324 ,  0.02798227, -1.31616399, -0.7224163 ,  0.21691841,
        1.28971527])

In [19]:
np.add(arr1, arr2) ##arr1 va arr2 elementlarini mos ravishda qo'shib beradi

array([-1.27699776, -0.45926797, -0.3101084 ,  0.22148412, -1.53009741,
        0.72181934])

In [20]:
arr1+arr2

array([-1.27699776, -0.45926797, -0.3101084 ,  0.22148412, -1.53009741,
        0.72181934])

In [21]:
np.multiply(arr1, arr2) ##arr1 va arr2 elementlarini mos ravishda ko'paytirib beradi

array([-1.65336278, -0.01363437, -1.32413415, -0.68188905, -0.3789599 ,
       -0.73242406])

In [22]:
np.maximum(arr1, arr2) ##ikki elementlarni taqqoslab, eng kattasini qaytaradi

array([0.79713464, 0.02798227, 1.0060556 , 0.94390042, 0.21691841,
       1.28971527])